Internal permission system
This commit implement the permission system, while no commands to set it up has been introduced yet, this has been tested through the data explorer of rethinkdb.

**Tests passed**
-Commands are prioritary over categories in their scope
-Channel permissions are prioritary over global permissions
-Roles permissions are prioritary over channel permissions
-Highest role is the one being taken into account over lower roles (in the future though, lower roles should be taken into account 
if the permissions they change aren't changed by the highest one)
-Users permissions are prioritary over roles permissions
-Ultimately, if no permissions are set at all (even globally), it fallback to the default permissions
-The admin specific permissions work as expected
-If the database isn't available, default permissions are used
-The checks are ignored if the command has been used in DM

**Possible issue encountered**
Some weird 

Error: TypeError: Cannot read property 'name' of undefined
Stacktrace: TypeError: Cannot read property 'name' of undefined
    at Command.memberHasPermissions (D:\Programming_Projects\Felix_v4\indev\util\helpers\Command.js:152:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

spawned when all the permissions were removed through the data explorer to check if the fallback to default permissions was working. This disapeared after a restart and im not sure what happened